//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n OeSystems.ScriptableHttp.Configuration --verbose --ct=System.Collections.Generic.List`1 --collectionSettersMode=Public Configuration.xsd
namespace OeSystems.ScriptableHttp.Configuration
{
    
    
    /// <summary>
    /// <para>The root of the configuration data.
    ///                Consists of a name, and set of sequentially performed operations.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("The root of the configuration data. Consists of a name, and set of sequentially p" +
        "erformed operations."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ScriptableHttpConfig", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Configuration", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    public partial class ScriptableHttpConfig
    {
        
        /// <summary>
        /// <para>A Name for a script or operation. Mostly this exists for logging.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<OperationConfig> _operation;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public System.Collections.Generic.List<OperationConfig> Operation
        {
            get
            {
                return _operation;
            }
            set
            {
                _operation = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ScriptableHttpConfig" /> class.</para>
        /// </summary>
        public ScriptableHttpConfig()
        {
            this._operation = new System.Collections.Generic.List<OperationConfig>();
        }
        
        /// <summary>
        /// <para>Defines a C# script that controls the order of operations.
        ///                If not Defined, each operation is called in sequence.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Script")]
        public string Script { get; set; }
    }
    
    /// <summary>
    /// <para>An operation represents the process of:
    ///                1. Build The URI from the HTTP options and Key-Values as needed.
    ///                2. Build the request headers using the Key-Values as needed.
    ///                3. Build the request body from the Request Template using the Key-Values as needed.
    ///                4. Make the HTTP request.
    ///                5. Update the Key-Values from the Response Headers as needed.
    ///                6. Update the Key-Values from the Response Body as needed.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"An operation represents the process of: 1. Build The URI from the HTTP options and Key-Values as needed. 2. Build the request headers using the Key-Values as needed. 3. Build the request body from the Request Template using the Key-Values as needed. 4. Make the HTTP request. 5. Update the Key-Values from the Response Headers as needed. 6. Update the Key-Values from the Response Body as needed.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OperationConfig", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OperationConfig
    {
        
        /// <summary>
        /// <para>A Name for a script or operation. Mostly this exists for logging.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Request")]
        public RequestConfig Request { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Response")]
        public ResponseConfig Response { get; set; }
    }
    
    /// <summary>
    /// <para>Defines the HTTP Method that will be used for a request.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Defines the HTTP Method that will be used for a request.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequestConfig", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestConfig
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Get")]
        public GetRequest Get { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Post")]
        public PostRequest Post { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GetRequest", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostRequest))]
    public partial class GetRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Culture")]
        public string Culture { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Uri")]
        public Uri Uri { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _timeoutSeconds = 10;
        
        [System.ComponentModel.DefaultValueAttribute(10)]
        [System.Xml.Serialization.XmlElementAttribute("TimeoutSeconds")]
        public int TimeoutSeconds
        {
            get
            {
                return _timeoutSeconds;
            }
            set
            {
                _timeoutSeconds = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<RequestHeader> _header;
        
        [System.Xml.Serialization.XmlElementAttribute("Header")]
        public System.Collections.Generic.List<RequestHeader> Header
        {
            get
            {
                return _header;
            }
            set
            {
                _header = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Header collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeaderSpecified
        {
            get
            {
                return ((this.Header != null) 
                            && (this.Header.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="GetRequest" /> class.</para>
        /// </summary>
        public GetRequest()
        {
            this._header = new System.Collections.Generic.List<RequestHeader>();
        }
    }
    
    /// <summary>
    /// <para>Defines the URI that will be used for the HTTP operation.
    ///                A Mapping can be used to alter the URI using the key-values prior to the request being made.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Defines the URI that will be used for the HTTP operation. A Mapping can be used t" +
        "o alter the URI using the key-values prior to the request being made."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("URI", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Uri
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<RegexMapping> _regex;
        
        [System.Xml.Serialization.XmlElementAttribute("Regex")]
        public System.Collections.Generic.List<RegexMapping> Regex
        {
            get
            {
                return _regex;
            }
            set
            {
                _regex = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Regex collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegexSpecified
        {
            get
            {
                return ((this.Regex != null) 
                            && (this.Regex.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Uri" /> class.</para>
        /// </summary>
        public Uri()
        {
            this._regex = new System.Collections.Generic.List<RegexMapping>();
        }
    }
    
    /// <summary>
    /// <para>Defines a mapping between a key-value pair and any kind of text that uses Regular Expressions.
    ///                The Value of the element must be a valid Regular Expression.
    ///                The key attribute identifies the name of the value to read or set.
    ///                May be used on requests, responses, the URI, or Custom Headers.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"Defines a mapping between a key-value pair and any kind of text that uses Regular Expressions. The Value of the element must be a valid Regular Expression. The key attribute identifies the name of the value to read or set. May be used on requests, responses, the URI, or Custom Headers.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RegexMapping", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegexMapping
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("key")]
        public string Key { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _required = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("required")]
        public bool Required
        {
            get
            {
                return _required;
            }
            set
            {
                _required = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("format")]
        public string Format { get; set; }
    }
    
    /// <summary>
    /// <para>Defines an HTTP Header that will be added to the request.
    ///                A Regex Map may be used update the value from the key-value pairs.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Defines an HTTP Header that will be added to the request. A Regex Map may be used" +
        " update the value from the key-value pairs."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RequestHeader", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestHeader
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<RegexMapping> _regex;
        
        [System.Xml.Serialization.XmlElementAttribute("Regex")]
        public System.Collections.Generic.List<RegexMapping> Regex
        {
            get
            {
                return _regex;
            }
            set
            {
                _regex = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Regex collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegexSpecified
        {
            get
            {
                return ((this.Regex != null) 
                            && (this.Regex.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RequestHeader" /> class.</para>
        /// </summary>
        public RequestHeader()
        {
            this._regex = new System.Collections.Generic.List<RegexMapping>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PostRequest", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostRequest : GetRequest
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("BodyTemplate")]
        public BodyTemplate BodyTemplate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Mappings")]
        public BodyMap Mappings { get; set; }
    }
    
    /// <summary>
    /// <para>Defines a block of text that will be used for the HTTP request body.
    ///                An XML CDATA block is especially useful for defining this value.
    ///                Not used for GET Requests.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Defines a block of text that will be used for the HTTP request body. An XML CDATA" +
        " block is especially useful for defining this value. Not used for GET Requests."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BodyTemplate", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BodyTemplate
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("contentType")]
        public string ContentType { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BodyMap", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BodyMap
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<XPathMapping> _xPath;
        
        [System.Xml.Serialization.XmlElementAttribute("XPath")]
        public System.Collections.Generic.List<XPathMapping> XPath
        {
            get
            {
                return _xPath;
            }
            set
            {
                _xPath = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the XPath collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XPathSpecified
        {
            get
            {
                return ((this.XPath != null) 
                            && (this.XPath.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BodyMap" /> class.</para>
        /// </summary>
        public BodyMap()
        {
            this._xPath = new System.Collections.Generic.List<XPathMapping>();
            this._jsonPath = new System.Collections.Generic.List<JsonPathMapping>();
            this._regex = new System.Collections.Generic.List<RegexMapping>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<JsonPathMapping> _jsonPath;
        
        [System.Xml.Serialization.XmlElementAttribute("JsonPath")]
        public System.Collections.Generic.List<JsonPathMapping> JsonPath
        {
            get
            {
                return _jsonPath;
            }
            set
            {
                _jsonPath = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the JsonPath collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JsonPathSpecified
        {
            get
            {
                return ((this.JsonPath != null) 
                            && (this.JsonPath.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<RegexMapping> _regex;
        
        [System.Xml.Serialization.XmlElementAttribute("Regex")]
        public System.Collections.Generic.List<RegexMapping> Regex
        {
            get
            {
                return _regex;
            }
            set
            {
                _regex = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Regex collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegexSpecified
        {
            get
            {
                return ((this.Regex != null) 
                            && (this.Regex.Count != 0));
            }
        }
    }
    
    /// <summary>
    /// <para>Defines a relationship between the key-value pairs and a value in XML structured data.
    ///                The value of the element must be a valid XPath.
    ///                The key attribute identifies the name of the value to read or set.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Defines a relationship between the key-value pairs and a value in XML structured " +
        "data. The value of the element must be a valid XPath. The key attribute identifi" +
        "es the name of the value to read or set."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("XPathMapping", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XPathMapping : BaseMapping
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BaseMapping", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JsonPathMapping))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XPathMapping))]
    public partial class BaseMapping
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Query")]
        public string Query { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<RegexMapping> _regex;
        
        [System.Xml.Serialization.XmlElementAttribute("Regex")]
        public System.Collections.Generic.List<RegexMapping> Regex
        {
            get
            {
                return _regex;
            }
            set
            {
                _regex = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Regex collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegexSpecified
        {
            get
            {
                return ((this.Regex != null) 
                            && (this.Regex.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BaseMapping" /> class.</para>
        /// </summary>
        public BaseMapping()
        {
            this._regex = new System.Collections.Generic.List<RegexMapping>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("key")]
        public string Key { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _required = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("required")]
        public bool Required
        {
            get
            {
                return _required;
            }
            set
            {
                _required = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("format")]
        public string Format { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _dataType = "System.String";
        
        [System.ComponentModel.DefaultValueAttribute("System.String")]
        [System.Xml.Serialization.XmlAttributeAttribute("dataType")]
        public string DataType
        {
            get
            {
                return _dataType;
            }
            set
            {
                _dataType = value;
            }
        }
    }
    
    /// <summary>
    /// <para>Defines a relationship between the key-value pairs and a value in JSON structured data.
    ///                The value of the element must be a valid JSON Path.
    ///                The key attribute identifies the name of the value to read or set.
    ///                Used for both creating the request from the template, and reading the response.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"Defines a relationship between the key-value pairs and a value in JSON structured data. The value of the element must be a valid JSON Path. The key attribute identifies the name of the value to read or set. Used for both creating the request from the template, and reading the response.")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("JsonPathMapping", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JsonPathMapping : BaseMapping
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ResponseConfig", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResponseConfig
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Culture")]
        public string Culture { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<ResponseHeader> _header;
        
        [System.Xml.Serialization.XmlElementAttribute("Header")]
        public System.Collections.Generic.List<ResponseHeader> Header
        {
            get
            {
                return _header;
            }
            set
            {
                _header = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Header collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeaderSpecified
        {
            get
            {
                return ((this.Header != null) 
                            && (this.Header.Count != 0));
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ResponseConfig" /> class.</para>
        /// </summary>
        public ResponseConfig()
        {
            this._header = new System.Collections.Generic.List<ResponseHeader>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Mappings")]
        public BodyMap Mappings { get; set; }
    }
    
    /// <summary>
    /// <para>Defines a header that is expected in the response</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Defines a header that is expected in the response")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ResponseHeader", Namespace="https://tempuri.org/ScriptableHttpConfiguration")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResponseHeader
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.Generic.List<RegexMapping> _regex;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Regex")]
        public System.Collections.Generic.List<RegexMapping> Regex
        {
            get
            {
                return _regex;
            }
            set
            {
                _regex = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ResponseHeader" /> class.</para>
        /// </summary>
        public ResponseHeader()
        {
            this._regex = new System.Collections.Generic.List<RegexMapping>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _required = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlAttributeAttribute("required")]
        public bool Required
        {
            get
            {
                return _required;
            }
            set
            {
                _required = value;
            }
        }
    }
}
